// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2riMUSctfE3p525HoSAlYpZjp6nnBxbw',
    appId: '1:949825680670:web:a0881faf5581ef8d2c050f',
    messagingSenderId: '949825680670',
    projectId: 'spotr-7c7e0',
    authDomain: 'spotr-7c7e0.firebaseapp.com',
    storageBucket: 'spotr-7c7e0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG5w9VFvPhka62axVO-VOZIT8f81-Q6pI',
    appId: '1:949825680670:android:91966a794cf76b452c050f',
    messagingSenderId: '949825680670',
    projectId: 'spotr-7c7e0',
    storageBucket: 'spotr-7c7e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8BAi5BFyfyUlUUEOaKPRKW6KCGxShvc8',
    appId: '1:949825680670:ios:154e595617adc8022c050f',
    messagingSenderId: '949825680670',
    projectId: 'spotr-7c7e0',
    storageBucket: 'spotr-7c7e0.appspot.com',
    iosClientId: '949825680670-n8eeava4db06epbu11qu0c84b7edkahg.apps.googleusercontent.com',
    iosBundleId: 'com.nutak.spotr',
  );
}
